// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlqtLll5ln9C0JV9tXZ9GpTLPxJfizNMo',
    appId: '1:828032333910:web:593a7e7738af88cac4e3f7',
    messagingSenderId: '828032333910',
    projectId: 'mindpal-1742f',
    authDomain: 'mindpal-1742f.firebaseapp.com',
    storageBucket: 'mindpal-1742f.firebasestorage.app',
    measurementId: 'G-NRBXZL3SL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFQkZZIsJgtVdjUFN_Tal9Yt-ek0oqDE',
    appId: '1:828032333910:android:f92a64f52512c277c4e3f7',
    messagingSenderId: '828032333910',
    projectId: 'mindpal-1742f',
    storageBucket: 'mindpal-1742f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Ek9cWtfauw-KAsSjXvnla9jU9jQ5hMA',
    appId: '1:828032333910:ios:81be476fc05daf7fc4e3f7',
    messagingSenderId: '828032333910',
    projectId: 'mindpal-1742f',
    storageBucket: 'mindpal-1742f.firebasestorage.app',
    iosBundleId: 'com.example.mindpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Ek9cWtfauw-KAsSjXvnla9jU9jQ5hMA',
    appId: '1:828032333910:ios:81be476fc05daf7fc4e3f7',
    messagingSenderId: '828032333910',
    projectId: 'mindpal-1742f',
    storageBucket: 'mindpal-1742f.firebasestorage.app',
    iosBundleId: 'com.example.mindpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlqtLll5ln9C0JV9tXZ9GpTLPxJfizNMo',
    appId: '1:828032333910:web:68b63e4fd78387d3c4e3f7',
    messagingSenderId: '828032333910',
    projectId: 'mindpal-1742f',
    authDomain: 'mindpal-1742f.firebaseapp.com',
    storageBucket: 'mindpal-1742f.firebasestorage.app',
    measurementId: 'G-25DMS9E7RG',
  );
}
